### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by petergerdes** [youtux/PebbleShows#1]
Steps to reproduce:
- Install from Pebble Store
- Successful connect with Trakt
- See white screen on Pebble

Details:
iPhone 6S on iOS 9.0.2
Pebble Time Steel

**Comment by kropochev** [comment]
I have the same problem
iPhone 5 iOS 9.1 App 3.4
Pebble Time Steel Watch 3.7

**Comment by youtux** [comment]
Sorry for the huge delay guys.
